name: flutter_amap_base_example
description: Example app for flutter_amap_base
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: "^3.10.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_amap_base:
    path: ../

flutter:
  uses-material-design: true
